# Generated by Django 2.1.5 on 2019-01-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='project_duration',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
