# Generated by Django 2.1.5 on 2019-02-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='brief',
            field=models.CharField(max_length=300),
        ),
    ]
