# Generated by Django 2.1.5 on 2019-02-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190206_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Client_technologies',
            field=models.CharField(default='brief', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='OS',
            field=models.CharField(default=str, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='Server_technologies',
            field=models.CharField(default=str, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='db',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='framework',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='host_engine',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='version_control',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='web_server',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
