# Generated by Django 2.1.5 on 2019-02-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20190206_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Client_technologies',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='OS',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='Server_technologies',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='db',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='framework',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='host_engine',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='version_control',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='web_server',
            field=models.CharField(max_length=30),
        ),
    ]
